spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  #thymeleaf
  thymeleaf:
    cache: false

server:
  servlet:
    context-path: /news

mybatis:
  mapper-locations: classpath:mapper/*.xml